apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: agendamentos
type: Opaque
stringData:
  POSTGRES_USER: agendamento
  POSTGRES_PASSWORD: "20241si000"
  POSTGRES_DB: agendamentos_db
