apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: agendamentos
data:
  nginx.conf: |
    events {}

    http {
        include /etc/nginx/mime.types;

        upstream backend {
            server fastapi:8080;
        }

        server {
            listen 80;
            listen 443 ssl;
            server_name localhost;

            ssl_certificate     /etc/nginx/certs/cert.pem;
            ssl_certificate_key /etc/nginx/certs/key.pem;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }

            location /api/ {
                proxy_pass http://backend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: agendamentos
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
