events {} # Obrigatório, mesmo vazio

http {
    include /etc/nginx/mime.types;

    upstream backend {
        server fastapi:8080;
    }

    server {
        listen 8080;
        listen 8443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Frontend e Backend em um lugar só para economizar linhas
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}